[website]
scholar = "scholar.google.co.uk"
"math fly" = "mathfly.org"
twitter = "twitter.com/home"
SMS = "https://mightytext.net/web8/"
youtube = "youtube.com"
times = "thetimes.co.uk"
maps = "https://www.google.com/maps"
amazon = "smile.amazon.co.uk"
VLE = "https://vle.york.ac.uk"
facebook = "facebook.com"
exams = "https://www.york.ac.uk/economics/current-students/ug-information/exampapers/#tab-2"
spectator = "spectator.co.uk"
kindle = "https://smile.amazon.co.uk/Kindle-eBooks-books/b/ref=nav_shopall_kbo5?ie=UTF8&node=341689031"
timetable = "timetable.york.ac.uk"
iPlayer = "https://www.bbc.co.uk/iplayer"
calendar = "https://www.google.com/calendar"
"what's app" = "https://web.whatsapp.com/"

[folder]
summer = "C:\\Users\\Mike\\Documents\\summer of stats"
mike = "C:\\Users\\Mike"
"app data" = "C:\\Users\\Mike\\AppData"
"math fly" = "C:\\Users\\Mike\\Documents\\NatLink\\mathfly"
downloads = "C:\\Users\\Mike\\Downloads"
"git hub" = "C:\\Users\\Mike\\Documents\\GitHub"
"saved images" = "C:\\Users\\Mike\\Pictures\\saved"
"queue tea" = "C:\\Users\\Mike\\Pictures\\pol\\qt"
documents = "C:\\Users\\Mike\\Documents"
sea = "C:\\"
papers = "C:\\Users\\Mike\\Documents\\papers"
films = "E:\\films"
pictures = "C:\\Users\\Mike\\Pictures"
caster = "C:\\Users\\Mike\\Documents\\NatLink\\caster"
e-books = "C:\\Users\\Mike\\Documents\\ebooks"

[program]
spotify = "C:\\Users\\Mike\\AppData\\Roaming\\Spotify\\Spotify.exe"
licks = "C:\\Program Files (x86)\\LyX 2.3\\bin\\LyX.exe"
"scientific notebook" = "C:\\Program Files (x86)\\Scientific Notebook\\scinoteb.exe"
chrome = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
"our studio" = "C:\\Program Files\\RStudio\\bin\\rstudio.exe"
Kindle = "C:\\Users\\Mike\\AppData\\Local\\Amazon\\Kindle\\application\\Kindle.exe"
torrent = "C:\\Program Files (x86)\\uTorrent\\uTorrent.exe"
sublime = "C:\\Program Files\\Sublime Text 3\\sublime_text.exe"

[file]
