[app]
Python = false
R = false
GitBash = false
Markdown = false
"Scientific notebook" = false

[global]
Go = false
Core = true
"LaTeX maths" = false
"LyX maths" = false
LaTeX = false

[selfmod]
variable = true
