# Once you have finished making changes, use the "rebuild caster"
# command to enact them.
"numbers_max"          = 500
"pronunciation"        = "Core"
"capitals_prefix"      = "big"
"numbers_prefix"       = "numb"
"dictation_prefix"     = "(say)"
"extreme"              = "wally"

[directories]
"app data"  =  "C:\\Users\\Mike\\AppData"
"caster"    =  "C:\\Users\\Mike\\Documents\\NatLink\\caster"
"documents" =  "C:\\Users\\Mike\\Documents"
"downloads" =  "C:\\Users\\Mike\\Downloads"
"summer"    =  "C:\\Users\\Mike\\Documents\\summer of stats"
"mike"      =  "C:\\Users\\Mike"
"e-books"   =  "C:\\Users\\Mike\\Documents\\ebooks"
"films"     =  "E:\\films"
"git hub"   =  "C:\\Users\\Mike\\Documents\\GitHub"
"math fly"  =  "C:\\Users\\Mike\\Documents\\NatLink\\mathfly"
"papers"    =  "C:\\Users\\Mike\\Documents\\papers"
"pictures"  =  "C:\\Users\\Mike\\Pictures"
"queue tea" =  "C:\\Users\\Mike\\Pictures\\pol\\qt"
"sea"       =  "C:\\"

[search]
"amazon"   = "https://smile.amazon.co.uk/s?k=%s"
"kindle"   = "https://smile.amazon.co.uk/s?k=%s&rh=n%%3A341689031"
"morrisons"= "https://groceries.morrisons.com/search?entry=%s"
"wikipedia"= "https://en.wikipedia.org/w/index.php?search=%s"
"google"   = "https://www.google.com/search?q=%s"
"youtube"  = "https://www.youtube.com/results?search_query=%s"

[letters_alt]
"(anti | arch)"        = "a"
"bat"                  = "b"
"cap"                  = "c"
"die"                  = "d"
"each"                 = "e"
"fail"                 = "f"
"(gone)"               = "g"
"(harp)"               = "h"
"sit"                  = "i"
"jury"                 = "j"
"crunch"               = "k"
"look"                 = "l"
"(made)"               = "m"
"near"                 = "n"
"odd"                  = "o"
"(pet)"                = "p"
"queer"                = "q"
"red"                  = "r"
"sun"                  = "s"
"trap"                 = "t"
"urge"                 = "u"
"vest"                 = "v"
"whale"                = "w"
"box"                  = "x"
"yes"                  = "y"
"zulu"                 = "z"

[punctuation]
"apostrophe"              = "apostrophe"
"backslash"               = "backslash"
"backtick"                = "backtick"
"caret"                   = "caret"
"comma"                   = "comma"
"boom"                    = "comma, space"
"dollar"                  = "dollar"
"point"                   = "dot"
"thin quotes"             = "apostrophe"
"(quote | quotes)"        = "dquote"
"equals"                  = "equal"
"hashtag"                 = "hash"
"hyphen"                  = "hyphen"
"semicolon"               = "semicolon"
"single quote"            = "squote"
"tilde"                   = "tilde"
"underscore"              = "underscore"
"greater than"            = "rangle"
"greater equal"           = "rangle, equal"
"less than"               = "langle"
"less equal"              = "langle, equal"
"equal to"                = "space, equal, equal, space"
"angle"                   = "langle, rangle, left"
"prekris"                 = "lparen, rparen, left"
"brax"                    = "lbracket, rbracket, left"
"curly"                   = "lbrace, rbrace, left"
"left paren"              = "lparen"
"(right | close) paren"   = "rparen"
"left bracket"            = "lbracket"
"(right | close) bracket" = "rbracket"
"left brace"              = "lbrace"
"(right | close) brace"   = "rbrace"

[punctuation2]
"ampersand"               = "ampersand"
"(starling)"              = "asterisk"
"at sign"                 = "at"
"pipe symbol"             = "bar"
"colon"                   = "colon/3"
"clamor"                  = "exclamation"
"minus"                   = "minus"
"modulo"                  = "percent"
"plus"                    = "plus"
"questo"                  = "question"
"slash"                   = "slash"

[keys]
"ace"                  = "space"
# "tabby"              = "tab"
# "tabby left"         = "s-tab"
"shock"                = "enter"
"clear"                = "backspace"
# "splat"              = "c-backspace"
# "splat right"        = "c-delete"
"deli"                 = "del"

[misc_core_keys]
"eskimo"               = "escape"
"(easter)"             = "end"
"(wester | homer)"     = "home"
"shackle"              = "home, s-end"
"select all"           = "c-a"
"find"                 = "c-f"
"and save"             = "c-s"

[misc_core_keys_noCCR]
"save"                 = "c-s"

[directions]
"left"                 = "left"
"right"                = "right"
"up"                   = "up"
"down"                 = "down"

[directions_alt]
"lease"                = "left"
"ross"                 = "right"
"sauce"                = "up"
"dunce"                = "down"

[modifiers]
"queue"                = "cs"
"shin"                 = "s"
"fly"                  = "c"

[enclosures]
"prekris"              = "(~)"
"angle"                = "<~>"
"curly"                = "{~}"
"brax"                 = "[~]"
"thin quotes"          = "'~'"
'quotes'               = '"~"'
'backticks'            = '`~`'

[capitalization]
"yell"                 = 1
"tie"                  = 2
"(Gerrish | camel)"    = 3
"sing"                 = 4
"laws"                 = 5
"password"             = 6

[spacing]
"gum"                  = 1
"gun"                  = 1
"spine"                = 2
"snake"                = 3
"pebble"               = 4
"incline"              = 5
"dissent"              = 6
"descent"              = 6
"list"                 = 7
"dictionary"           = 8


[letters]
"alpha"                = "a"
"bravo"                = "b"
"charlie"              = "c"
"delta"                = "d"
"echo"                 = "e"
"foxtrot"              = "f"
"golf"                 = "g"
"hotel"                = "h"
"india"                = "i"
"juliet"               = "j"
"kilo"                 = "k"
"lima"                 = "l"
"mike"                 = "m"
"november"             = "n"
"oscar"                = "o"
"papa"                 = "p"
"quebec"               = "q"
"romeo"                = "r"
"sierra"               = "s"
"tango"                = "t"
"uniform"              = "u"
"victor"               = "v"
"whiskey"              = "w"
"x-ray"                = "x"
"yankee"               = "y"
"zulu"                 = "z"
