"pronunciation" = "Git Bash"
"executable_contexts" = ["\\sh.exe", "\\bash.exe", "\\cmd.exe", "\\mintty.exe", "powershell"]

[commands]
"bash"           = "bash "
"cancel"         = ["", "c-c"]
"CD up"          = ["cd ..", "enter"]
"CD"             = "cd "
"dot PDF"        = ".pdf"
"dot jay peg"    = ".jpg"
"dot PNG"        = ".png"
"dot pie"        = ".py"
"dot tex"        = ".tex"
"(LS | list)"    = "ls "
"line count"     = "wc -l "
"make directory" = "mkdir "
"move file"      = "mv  "
"pipe"           = " | "
"lodge and"      = " && "
"Sumatra [PDF]"  = "SumatraPDF "
"to file"        = " > "
"sed replace"    = ["sed -i -e \"s///g\"", "left:4"]
"jupiter notebook" = "jupyter notebook"
#------------------------------------------------------
# latex
"PDF LaTeX"              = "pdflatex "
"bib TeX"                = "bibtex "
"pan doc"                = ["pandoc \"\" -o \"", "left:6"]
"pan doc beamer"         = ["pandoc  -t beamer -o ", "left:14"]
#------------------------------------------------------
# python
"python 3"               = ["python3 .py", "left:3"]
"python 2"               = ["python27 .py", "left:3"]
"python 2 64 "           = "C:/Python27-64/python.exe "
"python 2 pip [install]" = "python27 -m pip install "
"python 3 pip [install]" = "python3 -m pip install "
"pip two (install | build) package" = "pip2 install -e ."
#------------------------------------------------------
# r
"R script"               = ["Rscript .r", "left:2"]
"R markdown"             = ["Rscript -e \"rmarkdown::render('.Rmd', clean=TRUE)\"", "left:19"]
#------------------------------------------------------
# jekyll
"jekyll serve watch"     = "jekyll serve --watch"
"jekyll build"           = "jekyll build"
"jekyll"                 = "jekyll "
#------------------------------------------------------
# image
"image [magic] trim"     = ["convert  -fuzz 1% -trim +repage ", "left:24"]
"image [magic] transparent"     = ["convert  -fuzz 1% -transparent white ", "left:29"]
"rename PNG large" = "rename 'png_large' 'png' *.png_large"
"rename jay peg large" = "rename 'jpg_large' 'jpg' *.jpg_large"
#------------------------------------------------------
# git
"generate change log" = ["github_changelog_generator /", "left"]
"generate mathfly change log" = ["github_changelog_generator mrob95/mathfly", "left"]
"(undo changes | git reset hard)"              = "git reset --hard"
"git (abort cherry pick | cherry pick abort)"  = "git cherry-pick --abort"
"git (branch delete | delete branch)" = "git branch -D "
"git (checkout branch | new branch)"  = "git checkout -b "
"git (GUI | gooey)"                   = "git gui"
"git add all"                         = "git add -A"
"git add"                             = "git add "
"git remove"                          = "git rm "
"git base"                            = "git "
"git blame"                           = "git blame PATH -L FIRSTLINE,LASTLINE"
"git branch set upstream [to]"        = "git branch --set-upstream-to="
"git branch"                          = "git branch "
"git checkout develop"                = ["git checkout develop", "enter"]
"git checkout master"                 = ["git checkout master", "enter"]
"git checkout upstream develop"       = ["git checkout upstream/develop", "enter"]
"git checkout"                        = "git checkout "
"git cherry pick"                     = "git cherry-pick "
"git clone github"                    = ["git clone https://github.com/.git", "left:4"]
"git clone"                           = "git clone "
"git commit all"                      = ["git commit -a -m \"\"", "left"]
"git commit"                          = ["git commit -m \"\"", "left"]
"git diff"                            = "git diff"
"git discard"                         = "git checkout -- "
"git (discard all | reset hard)"      = "git reset --hard"
"git fetch upstream"                  = "git fetch upstream"
"git fetch upstream and pull"         = "git fetch upstream && git pull"
"git fetch origin"                    = "git fetch origin"
"git fetch origin and pull"           = "git fetch origin && git pull"
"git fetch"                           = "git fetch "
"git gooey blame"                     = "git gui blame PATH"
"git hub"                             = "https://github.com/"
"git init"                            = "git init"
"git log"                             = "git log"
"git merge tool"                      = "git mergetool"
"git merge"                           = "git merge "
"git publish"                         = "git push -u origin "
"git pull"                            = "git pull "
"git push set upstream [origin]"      = "git push --set-upstream origin "
"git push"                            = "git push "
"git rebase"                          = "git rebase "
"git remote add origin"               = "git remote add origin "
"git remote"                          = "git remote "
"git remove branch"                   = "git branch -d "
"git reset"                           = "git reset"
"git stash branch"                    = "git stash branch NAME"
"git stash list"                      = "git stash list"
"git stash"                           = "git stash"
"git unstage"                         = "git reset -- "
"git (stash pop | retrieve)"          = "git stash pop"
"git status"                          = ["git status", "enter"]