
[elements]
"abbreviation" = ["<abbr></abbr>", "left:7"]
"address " = ["<address>", "enter", "</address>", "up"]
"anchor" = ["<a></a>", "left:4"]
"area" = ["<area />", "left:2"]
"article " = ["<article >"]
"audio" = ["<audio>", "enter", "</audio>", "up"]
"base" = ["<base >", "left:1"]
"body" = ["<body>", "enter:2", "</body>", "up"]
"bold" = ["<b></b>", "left:4"]
"break | be are | BR" = ["<br>", "enter"]
"button" = ["<button></button>", "left:9"]
"canvas close" = ["</canvas>"]
"canvas" = ["<canvas >", "left:1"]
"checkbox" = ["<input type=\"checkbox\">"]
"close article" = ["</article>"]
"code" = ["<code></code>", "left:7"]
"content" = ["<content>"]
"data list" = ["<datalist>", "enter", "</datalist>", "up"]
"data" = ["<data></data>", "left:7"]
"decorator" = ["<decorator>"]
"defining instance" = ["<dfn></dfn>", "left:6"]
"deleted text | deleted | replaced" = ["<del></del>", "left:6"]
"description | DD" = ["<dd>"]
"details" = ["<details>"]
"dialog" = ["<dialog>"]
"division" = ["<div></div>", "left:6"]
"DOC TYPE" = ["<!DOCTYPE html>", "enter"]
"element" = ["<element>"]
"embedded" = ["<embed >", "left:1"]
"embraces pronunciation | RT" = ["<rt></rt>", "left:5"]
"emphasis | EM" = ["<em></em>", "left:5"]
"fall-back parenthesis | RP" = ["<rp></rp>", "left:5"]
"field set close" = ["</fieldset>"]
"field set" = ["<fieldset>", "enter", "</fieldset>", "up"]
"fig caption" = ["<figcaption>"]
"figure" = ["<figure>"]
"footer" = ["<footer>", "enter", "</footer>", "up"]
"form" = ["<form>", "enter", "</form>", "up"]
"H 1 | heading one" = ["<h1></h1>", "left:5"]
"H 2 | heading to" = ["<h2></h2>", "left:5"]
"H 3 | heading three" = ["<h3></h3>", "left:5"]
"H 4 | heading for" = ["<h4></h4>", "left:5"]
"H 5 | heading five" = ["<h5></h5>", "left:5"]
"H 6 | heading six" = ["<h6></h6>", "left:5"]
"H are | HR" = ["<hr>"]
"H group | headings group" = ["<hgroup></hgroup>", "left:9"]
"head" = ["<head>", "enter", "</head>", "up"]
"header" = ["<header>", "enter", "</header>", "up"]
"HTML" = ["<html>", "enter", "</html>", "up"]
"image " = ["<img></img>", "left:6"]
"inline frame close" = ["</iframe>", "left:1"]
"inline frame" = ["<iframe >", "left:1"]
"input" = ["<input >", "left:1"]
"inserted text | inserted" = ["<ins></ins>", "left:6"]
"isolate | bi-directional isolation" = ["<bdi></bdi>", "left:6"]
"keyboard input" = ["<kbd></kbd>", "left:6"]
"keygen" = ["<keygen >", "left:1"]
"label close" = ["</label>"]
"label" = ["<label>"]
"legend" = ["<legend>"]
"link" = ["<a href=''></a>", "left:6"]
"list element | DL" = ["<dl>"]
"list item | LI" = ["<li></li>", "left:5"]
"main" = ["<main>", "enter", "</main>", "up"]
"map" = ["<map>", "enter", "</map>", "up"]
"mark | highlight" = ["<mark></mark>", "left:7"]
"menu item" = ["<menuitem>"]
"menu" = ["<menu>"]
"meta" = ["<meta >", "left:1"]
"meter close" = ["</meter>"]
"meter" = ["<meter >", "left:1"]
"navigation | navigate" = ["<nav>", "enter", "</nav>", "up"]
"noscript" = ["<noscript>", "enter", "</noscript>", "up"]
"object| embedded object" = ["<object >", "left:1"]
"opt group" = ["<optgroup>", "enter", "</optgroup>", "up"]
"option close" = ["</option>"]
"option" = ["<option >", "left:1"]
"optional break" = ["<wbr></wbr>", "left:6"]
"ordered list | OL" = ["<ol>", "enter", "</ol>", "up"]
"output close" = ["</output>"]
"output" = ["<output >", "left:1"]
"override" = ["<bdo></bdo>", "left:6"]
"paragraph" = ["<p>", "enter", "</p>", "up"]
"parameter " = ["<param >", "left:1"]
"pre-format" = ["<pre>", "enter", "</pre>", "up"]
"progress" = ["<progress >", "left:1"]
"quote" = ["<q></q>", "left:4"]
"ruby | pronounce asian" = ["<ruby></ruby>", "left:7"]
"sample output" = ["<samp></samp>", "left:7"]
"script" = ["<script></script>", "left:9"]
"section" = ["<section>", "enter", "</section>", "up"]
"select" = ["<select>", "enter", "</select>", "up"]
"semantics | italics" = ["<i></i>", "left:4"]
"shadow" = ["<shadow>"]
"small" = ["<small></small>", "left:8"]
"source" = ["<source >", "left:1"]
"span" = ["<span></span>", "left:7"]
"strong" = ["<strong></strong>", "left:9"]
"style close" = ["</style>"]
"style" = ["<style >", "left:1"]
"subscript" = ["<sub></sub>", "left:6"]
"summary" = ["<summary>"]
"superscript" = ["<sup></sup>", "left:6"]
"table body" = ["<tbody>"]
"table caption | tee caption" = ["<caption>"]
"table cell | TD | tee D" = ["<td></td>", "left:5"]
"table column group | tee group" = ["<colgroup>"]
"table column | tee column" = ["<col>"]
"table foot" = ["<tfoot>"]
"table head | thead" = ["<thead>"]
"table header | TH" = ["<th>"]
"table row | tee are" = ["<tr></tr>", "left:5"]
"table" = ["<table>"]
"template" = ["<template>"]
"text area close" = ["</textarea>"]
"text area" = ["<textarea >", "left:1"]
"time" = ["<time></time>", "left:7"]
"title" = ["<title></title>", "left:8"]
"track" = ["<track >", "left:1"]
"underline" = ["<u></u>", "left:4"]
"unordered list | UL" = ["<ul>", "enter", "</ul>", "up"]
"variable" = ["<var></var>", "left:6"]
"video close" = ["</video>"]
"video" = ["<video >", "left:1"]