# Once you have finished making changes, use the "rebuild mathfly"
# command to enact them.
"pronunciation" = "LaTeX"
# Insert your own .bib file here, e.g.
# "bibliography_path" = "C:/Users/Mike/Documents/bibliography.bib"
"bibliography_path"  = "C:/Users/Mike/Documents/1_uni_work/bibliography.bib"
"class_prefix"       = "document class"
"environment_prefix" = "begin"
"package_prefix"     = "use package"
"symbol_prefix"      = "symbol"
"greek_prefix"       = "greek"
"command_prefix"     = "insert"
"template_prefix"    = "template"
"accent_prefix"      = "accent"

[document_classes]
"article"     = "article"
"beamer"      = "beamer"
"book"        = "book"
"letter"      = "letter"
"proceedings" = "proc"
"report"      = "report"

[packages]
"AMS math"    = "amsmath"
"bib latex"   = ["[backend=bibtex,style=authoryear]", "biblatex"]
"colour"      = "color"
"geometry"    = "geometry"
"hyper ref"   = "hyperref"
"graphic X"   =  "graphicx"
"math tools"  =  "mathtools"
"multi col"   = "multicol"
"long table"  = "longtable"
"tabular X"   = "tabularx"
"X color"     = "xcolor"
"wrap figure" =  "wrapfig"

# These commands produce begin and end tags, and end inside.
# if included, the second element in lists come after the first begin
# tag. For example, "begin figure" produces
# \begin{figure}[h!]
# \end{figure}
[environments]
"abstract"                    = "abstract"
"add margin"                  = "addmargin"
"align"                       = "align"
"center"                      = "center"
"columns"                     = "columns"
"column"                      = ["column", "{0.5\\textwidth}"]
"description"                 = "description"
"document"                    = "document"
"(enumerate | numbered list)" = "enumerate"
"equation"                    = "equation"
"figure"                      = ["figure", "[h!]"]
"flush left"                  = "flushleft"
"flush right"                 = "flushright"
"frame"                       = "frame"
"(list | itemise)"            = "itemize"
"mini page"                   = "minipage"
"multi (cols | columns)"      = ["multicols", "{2}"]
"multi line"                  = "multiline"
"quotation"                   = "quotation"
"quote"                       = "quote"
"split"                       = "split"
"table"                       = ["table", "[h!]\n\\centering"]
"long table"                  = ["longtable", "{lll}"]
"tabular"                     = ["tabular", "{llll}"]
"tabular X"                   = ["tabular X", "{l X}"]
"theorem"                     = "theorem"
"title page"                  = "titlepage"
"verbatim"                    = "verbatim"
"verse"                       = "verse"
"wrap figure"                 = "wrapfigure"


[command]
"author"                      = "author"
"[add] bib resource"          = "addbibresource"
"caption"                     = "caption"
"(cite | citation)"           = "cite"
"chapter"                     = "chapter"
"frame title"                 = "frametitle"
"foot cite"                   = "footcite"
"footnote"                    = "footnote"
"footnote text"               = "footnotetext[]"
"graphics path"               = "graphicspath"
"[include] graphics"          = "includegraphics[width=1\\textwidth]"
"input"                       = "input"
"label"                       = "label"
"new command"                 = "newcommand{}[]"
"no cite"                     = "nocite"
"paragraph"                   = "paragraph"
"paren cite"                  = "parencite"
"part"                        = "part"
"reference"                   = "ref"
"renew command"               = "renewcommand"
"sub paragraph"               = "subparagraph"
"(section | heading)"         = "section"
"sub (section | heading)"     = "subsection"
"sub sub (section | heading)" = "subsubsection"
"text cite"                   = "textcite"
"text color"                  = "textcolor{}"
"[text] bold"                 = "textbf"
"[text] italics"              = "textit"
"[text] slanted"              = "textsl"
"title"                       = "title"
"use theme"                   = "usetheme"
#
"grave [accent]"              = "`"
"acute [accent]"              = "'"
"dot [accent]"                = "."
"breve [accent]"              = "u"
"(circumflex | hat)"          = "^"
"(umlaut | dieresis)"         = "\""
"(tilde | squiggle)"          = "~"
"(macron | bar)"              = "="

[commandnoarg]
"tiny text"          = "tiny"
"small text"         = "small"
"normal size text"   = "normalsize"
"large text"         = "large"
"quite large text"   = "Large"
"very large text"    = "LARGE"
"huge text"          = "huge"
"very huge text"     = "Huge"
"centering"          = "centering"
"column"             = "column{0.5\\textwidth}"
"footnote mark"      = "footnotemark[]"
"horizontal line"    = "hline"
"(lah | lay) tech"   = "LaTeX~"
"line break"         = "linebreak"
"[list] item"        = "item"
"make title"         = "maketitle"
"new page"           = "newpage"
"no indent"          = "noindent"
"page break"         = "pagebreak"
"print bibliography" = "printbibliography"
"table of contents"  = "tableofcontents"
"tech"               = "TeX~"
"text backslash"     = "textbackslash"
"text height"        = "textheight"
"text width"         = "textwidth"
"(verb | verbatim)"  = "verb||"
"vertical line"      = "vline"


[greek_letters]
"alpha"       = "alpha"
"beater"      = "beta"
"gamma"       = "gamma"
"delta"       = "delta"
"epsilon"     = "epsilon"
"var epsilon" = "varepsilon"
"zita"        = "zeta"
"eater"       = "eta"
"theta"       = "theta"
"iota"        = "iota"
"kappa"       = "kappa"
"lambda"      = "lambda"
"mu"          = "mu"
"new"         = "nu"
"zee"         = "xi"
"cherry"      = "pi"
"row"         = "rho"
"sigma"       = "sigma"
"tau"         = "tau"
"upsilon"     = "upsilon"
"phi"         = "phi"
"chi"         = "chi"
"sigh"        = "psi"
"omega"       = "omega"


[misc_symbols]
"inline" = ["$$", "left"]
"super [script]"            = ["^{}", "left"]
"sub [script]"              = ["_{}", "left"]
"squared"                   = "^{2} "
"cubed"                     = "^{3} "
"inverse"                   = "^{-1} "
"degrees"                   = "^{\\circ}"
"(parens | parentheses)"    = ["\\left(  \\right) ", "left:9"]
"square brackets"           = ["\\left[  \\right] ", "left:9"]
"(curly brackets | braces)" = ["\\{  \\} ", "left:4"]

# if included, a number as the second element in a list
# puts that number of curly braces after the command, e.g.
# "symbol fraction" produces "\frac{}{}"
[symbols]
"quad"                                      = "quad"
"double quad"                               = "qquad"
"square root"                               = ["sqrt", "1"]
"[generic] root"                            = ["sqrt[]", "1"]
"integral"                                  = "int"
"double integral"                           = "iint"
"triple integral"                           = "iiint"
"infinity"                                  = "infty"
"times"                                     = "times"
"divide"                                    = "div"
"intersection"                              = "cap"
"union"                                     = "cup"
"C dot"                                     = "cdot"
"summation"                                 = "sum"
"product"                                   = "prod"
"(direct sum | oh plus)"                    = "oplus"
"(large direct sum | large oh plus)"        = "bigoplus"
"plus or minus"                             = "pm"
"partial"                                   = "partial"
"tilde"                                     = "sim"
#
"fraction"                                  = ["frac", "2"]
"unit"                                      = "unitone"
"unit two"                                  = "unittwo"
"unit fraction "                            = "unitfrac"
"text fraction"                             = "tfrac"
"display fraction"                          = "dfrac"
"continued fraction"                        = "cfrac"
"continued fraction (left)"                 = "cfracleft"
"continued fraction (right)"                = "cfracright"
"binomial"                                  = "choose"
# "text binomial"                           = "tbinom"
# "display binomial"                        = "dbinom"
# trig
"sine"                                      = "sin"
"cosine"                                    = "cos"
"tangent"                                   = "tan"
"secant"                                    = "sec"
"cosecant"                                  = "csc"
"cotangent"                                 = "cot"
"arc sine"                                  = "arcsin"
"arc cosine"                                = "arccos"
"arc tan"                                   = "arctan"
"hyperbolic sine"                           = "sinh"
"hyperbolic cosine"                         = "cosh"
"hyperbolic cotangent"                      = "coth"
"hyperbolic tangent"                        = "tanh"
# functions
"argument"                                  = "arg"
"modulus"                                   = "bmod"
"degree"                                    = "deg"
"determinant"                               = "det"
"dimension"                                 = "dim"
"exp"                                       = "exp"
"GCD"                                       = "gcd"
"cat hom"                                   = "hom"
"kernel"                                    = "ker"
"infimum"                                   = "inf"
"supremum"                                  = "sup"
"limit"                                     = "lim"
"liminf"                                    = "liminf"
"(natural (log | logarithm) | log natural)" = "ln"
"logarithm"                                 = "log"
"max"                                       = "max"
"min"                                       = "min"
"probability"                               = "Pr"
# relations
"[is] not equal [to]"                       = "neq"
"[is] greater [than] [or] equal [to]"       = "geq"
"[is] less [than] [or] equal [to]"          = "leq"
"[is] approximately [equal] [to]"           = "approx"
"proportional [to]"                         = "propto"
"preference less [than]"                    = "prec"
"preference less equals"                    = "preceq"
"preference greater [than]"                 = "succ"
"preference greater equals"                 = "succeq"
# sets
"subset"                                    = "subset"
"superset"                                  = "supset"
"strict subset"                             = "subsetneq"
"strict superset"                           = "supsetneq"
"member"                                    = "in"
# logic
"(land|logic and)"                          = "land"
"logic or"                                  = "lor"
"primer"                                    = "prime"
"logic not"                                 = "lnot"
"for all"                                   = "forall"
"there exists"                              = "exists"
# math fonts
"(beebee|blackboard bold)"                  = "mathbb"
"roman"                                     = "mathrm"
"bold"                                      = "mathbf"
"bold symbol"                               = "boldsymbol"
"sans serif"                                = "mathsf"
"italic"                                    = "mathit"
"typewriter"                                = "matttt"
"blackboard"                                = "mathbb"
"fraktur"                                   = "mathfrak"
"calligraphic"                              = "mathcal"
"formal script"                             = "mathscr"
"normal text mode"                          = "textrm"
#
"real numbers"                              = "mathbb{R}"
"complex numbers"                           = "mathbb{C}"
"integer numbers"                           = "mathbb{Z}"
"rational numbers"                          = "mathbb{Q}"
"natural numbers"                           = "mathbb{N}"
#
"left arrow"                                = "leftarrow"
"right arrow"                               = "rightarrow"
"up arrow"                                  = "uparrow"
"down arrow"                                = "downarrow"
"left right arrow"                          = "leftrightarrow"
#
"left paren"                                = "left("
"right paren"                               = "right)"
#
"dot dot dot"                               = "dots"
"L dots"                                    = "ldots"
"diagonal dots"                             = "ddots"
"horizontal dots"                           = "cdots"
"vertical dots"                             = "vdots"

[accents]
"bar"        = "bar"
"breve"      = "breve"
"check"      = "check"
"dot"        = "dot"
"ddot"       = "ddot"
"hat"        = "hat"
"wide hat"   = "widehat"
"tilde"      = "tilde"
"wide tilde" = "widetilde"
"vector"     = "vec"

# These are longer and are pasted in rather than being executed
# as keystrokes. Add as many as you like.
[templates]
"header" = '''
\documentclass[12pt, a4paper]{article}

\usepackage[hidelinks]{hyperref}
\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage[backend=bibtex,style=authoryear]{biblatex}
\addbibresource{C:/Users/Mike/Documents/1_uni_work/bibliography.bib}

\setlength{\parskip}{1em}
\renewcommand{\baselinestretch}{1.3}
'''
# ------------------------------------------------
"beamer" = '''
\documentclass{beamer}
\usetheme{metropolis}
\usepackage{graphicx}
\usepackage[backend=bibtex,style=authoryear]{biblatex}
\addbibresource{C:/Users/Mike/Documents/1_uni_work/bibliography.bib}

\begin{document}
\begin{frame}
\frametitle{}

\end{frame}
\end{document}
'''
# ------------------------------------------------
"(graphic | figure)" = '''
\begin{figure}[h!]
\centering
\includegraphics[width=1\textwidth]{}
\caption{}
\label{}
\end{figure}
'''
# ------------------------------------------------
"wrap (graphic | figure)" = '''
\begin{wrapfigure}{l}{0.5\textwidth}
\centering
\includegraphics[width=0.4\textwidth]{}
\caption{}
\label{}
\end{wrapfigure}
'''
# ------------------------------------------------
"table" = '''
\begin{table}[h!]
\centering
\label{}
\begin{tabular}{ccccc}
&  &  &  & \\
\hline
&  &  &  &  \\
\end{tabular}
\caption{}
\end{table}
'''
# ------------------------------------------------