"pronunciation"   = "Markdown"
"title_contexts"  = [".md", ".Rmd", "GitHub", "Gitter", "Notepad"]
"insert_prefix"   = "insert"
"template_prefix" = "template"
"output_prefix"   = "output"
"option_prefix"   = "option"

[elements]
"list"                    = "asterisk, space"
"numbered list"           = "one, dot, space"
"[block] quote"           = "rangle, space"
"image"                   = "exclamation, lbracket, rbracket, lparen, rparen, left:3"
"code [block]"            = "backtick:6, left:3, s-enter:2, up"
"in-line code"            = "backtick:2, left"
"horizontal rule"         = "minus, minus, minus"
"heading"                 = "hash, space"
"subheading"              = "hash, hash, space "
"sub sub heading"         = "hashtag, hashtag, hashtag, space"
"link"                    = "lbracket, rbracket, lparen, rparen, left:3"
"reference"               = "lbracket, rbracket, left, at"
"equation"                = "dollar, dollar, s-enter:2, dollar, dollar, up"
"math"                    = "dollar, dollar, left"
"(italics | italic text)" = "underscore:2, left"
"bold [text]"             = "asterisk:4, left:2"
"R code"                  = "backtick:3, lbrace, r, rbrace, enter:2, backtick:3, up"

[alternating]
"hidden R code"         = ["", "backtick:3", "{r, include=FALSE}", "enter:2, backtick:3, up"]
"graph"                 = ["", "backtick:3", "{r echo=FALSE}", "enter:2, backtick:3, up"]

[outputs]
"beamer [presentation]" = "output:\nbeamer_presentation:\ndf_print: kable\ntheme: metropolis"
"HTML"                  = "output: html_document"
"PDF"                   = "output:\npdf_document:\ndf_print: kable"
"word"                  = "output:\nword_document"

[options]
"author"            = "author: "
"bibliography"      = "bibliography: "
"date"              = "date: "
"figure width"      = "fig_width: "
"figure height"     = "fig_height: "
"figure caption"    = "fig_caption: true"
"font size"         = "fontsize: 11pt"
"keep tex"          = "keep_tex: true"
"small output"      = "header-includes:\n- \\let\\oldverbatim\\verbatim\n- \\def\\verbatim{\\tiny \\oldverbatim}"
"table of contents" = "toc: true"
"title"             = "title: "

[templates]