["econometric analysis"]
path = "file:///C:/Users/Mike/Documents/1_uni_work/econometric%20methods%20research/wooldridge_j-_2002_econometric_analysis_of_cross_section_and_panel_data.pdf"
"random" = 200