pronunciation     = "R"
"title_contexts"  = [".r", "RStudio", "Rterm"]
function_prefix   = "fun"
"graph_prefix"    = "graph"
"model_prefix"    = "model"
"argument_prefix" = "meant"
"template_prefix" = "template"
"markdown_prefix" = "markdown"
library_prefix    = "library"

[commands]
"assign"              = " <- "
"add comment"         = "# "
"pipe"                = " %>% "
"data pipe"           = " %$% "
"chain"               = ["", "end", " %>%", "enter"]
"data chain"          = ["", "end", " %$%", "enter"]
"tell add"            = ["", "end, space, plus, enter"]
"iffae"               = ["if ()", "left"]
"shells"              = "else "
"breaker"             = "break"
"for each"            = ["for ( in )", "left:6"]
"for loop"            = ["for (i in 1:)", "left"]
"graph remove legend" = ["theme(legend.position = \"none\")"]
"while loop"          = ["while ()", "left"]
"lodge and"           = " & "
"lodge in"            = " %in% "
"lodge or"            = " | "
"function"            = ["function()", "left"]
"value null"          = "NULL"
"value NA"            = "NA"
"value true"          = "TRUE"
"value false"         = "FALSE"

[r_functions]
"anti join" = "anti_join"
"arrange"             = "arrange"
"as character"        = "as.character"
"as date"             = "as.Date"
"as data frame"       = "as.data.frame"
"as double"           = "as.double"
"as factor"           = "as.factor"
"as numeric"          = "as.numeric"
"bind rows"           = "bind_rows"
"cable"               = "kable"
"case when"           = "case_when"
"count"               = "count"
"covariance"          = "cov"
"correlation"         = "cor"
"distinct"            = "distinct"
"describe"            = "describe"
"drop NA"             = "drop_na"
"eigen"               = "eigen"
"everything"          = "everything"
"filter"              = "filter"
"full join"           = "full_join"
"gather"              = "gather"
"glimpse"             = "glimpse"
"group by"            = "group_by"
"haversine"           = "haversine"
"head"                = "head"
"if else"             = "ifelse"
"inner join"          = "inner_join"
"install packages"    = "install.packages"
"is NA"               = "is.na"
"(isn't | is not) NA" = "!is.na"
"left join"           = "left_join"
"length"              = "length"
"library"             = "library"
"list"                = "list"
"(LM | linear model)" = "lm"
"log"                 = "log"
"M table"             = "mtable"
"map"                 = "map"
"margins"             = "margins"
"max"                 = "max"
"min"                 = "min"
"mean"                = "mean"
"mutate"              = "mutate"
"names"               = "names"
"nest"               = "nest"
"paste"               = "paste0"
"print"               = "print"
"read CSV"            = "read_csv"
"read E views"        = "readEViews"
"read excel"          = "read_xlsx"
"read RDS"            = "read_rds"
"rename"              = "rename"
"reorder"             = "reorder"
"right join"          = "right_join"
"semi join"          = "semi_join"
"select"              = "select"
"scale"               = "scale"
"starts with"         = "starts_with"
"string contains"     = "str_contains"
"string detect"       = "str_detect"
"string replace"      = "str_replace"
"string replace all"  = "str_replace_all"
"subset"              = "subset"
"sum"                 = "sum"
"summarise"           = "summarise"
"summary"             = "summary"
"tail"                = "tail"
"tidy"                = "tidy"
"tibble"              = "tibble"
"trim white space"    = "trimws"
"type [of]"           = "typeof"
"ungroup"             = "ungroup"
"vector"              = "c"
"view"                = "View"
"vee table"           = "vtable"
"write RDS"           = "write_rds"
"write CSV"           = "write_csv"
"ex table"            = "xtable"
"un nest" = "unnest"

[libraries]
"cable"       = "kable"
"car"         = "car"
"gap minder"  = "gapminder"
"gee animate" = "gganimate"
"gee map"     = "ggmap"
"gee repel"   = "ggrepel"
"grid extra"  = "gridExtra"
"knitter"     = "knitr"
"LM test"     = "lmtest"
"margins"     = "margins"
"psych"       = "psych"
"stargazer"   = "stargazer"
"tidy verse"  = "tidyverse"
"vee table"   = "vtable"

[r_graph]
"aesthetics"                   = "aes"
"column [plot]"                = "geom_col"
"(coordinates | coords) fixed" = "coord_fixed"
"density [plot]"               = "geom_density"
"element blank"                = "element_blank"
"ex limit"                     = "xlim"
"facet grid"                   = "facet_grid"
"facet wrap"                   = "facet_wrap"
"histogram [plot]"             = "geom_histogram"
"labels"                       = "labs"
"error bar"                    = "errorbar"
"label"                        = "geom_label"
"text"                         = "geom_text"
"line [plot]"                  = "geom_line"
"path [plot]"                  = "geom_path"
"polygon [plot]"               = "geom_polygon"
"[GG] plot"                    = "ggplot"
"point [plot]"                 = "geom_point"
"save"                         = "ggsave"
"smooth [plot]"                = "geom_smooth"
"theme"                        = "theme"
"theme minimal"                = "theme_minimal"
"why limit"                    = "ylim"

[r_args]
"by"                                  = "by = "
"colour"                              = "colour = "
"dodge"                               = "\"dodge\""
"fill"                                = "fill = "
"header"                              = "header = "
"gather"                              = "key = \"\",\nvalue = \"\",\n"
"labels"                              = "x = \"\",\ny = \"\",\ntitle = \"\",\nsubtitle = \"\",\ncaption = \"\""
"LM"                                  = "\"lm\""
"method"                              = "method = "
"position"                            = "position = "
"year"                                = "year"

[r_model]
"arma"                                = "arima(,\norder = c(, 0, ),\ninclude.mean = TRUE)"
"ACF"                                 = "Acf()"
"PACF"                                = "Pacf()"
"chi square"                          = "qchisq"
"coefficients"                        = "coefficients"
"fixed effects"                       = "plm(,\ndata=,\nindex=c(,),\nmodel = \"within\")"
"fitted [values]"                     = "fitted.values"
"instrumental [variable]"             = "ivreg( ~  | ,\ndata = )"
"libraries"                           = "library(AER)\nlibrary(car)\nlibrary(stats)\nlibrary(DescTools)\nlibrary(plm)"
"(linear | LM)"                       =  "lm(, data=)"
"[(linear | test)] hypothesis [test]" =  "linearHypothesis(model = ,\nc(\" = 0\"),\ntest=c(\"F\", \"Chisq\"))"
"(log it)"                            = "glm(,\nfamily = binomial(link=\"logit\"),\ndata=)"
"log likelihood"                      = "logLik()"
"normal"                              = "pnorm(q = , mean = , sd = )"
"pro bit"                             = "glm(,\nfamily = binomial(link=\"probit\"),\ndata=)"
"(pseudo | McFadden) R squared"       = "PseudoR2(, which=\"McFadden\")"
"random effects"                      = "plm(,\ndata=,\nindex=c(,),\nmodel = \"random\")"
"residuals"                           = "residuals"

[markdown]
"graph"                               = ["", "backtick:3", "{r echo=FALSE}", "enter:2, backtick:3, up"]

[templates]
