# Once you have finished making changes, use the "rebuild caster"
# command to enact them.
"pronunciation" = "Scientific notebook"
"greek_prefix" = "greek"
"symbol_prefix" = ""
"accent_prefix" = "accent"
"unit_prefix" = "unit"

[greek_letters]
"alpha" = "a"
"beater" = "b"
"gamma" = "g"
"delta" = "d"
"epsilon" = "e"
"zita" = "z"
"eater" = "h"
"theta" = "y"
"iota" = "i"
"kappa" = "k"
"lambda" = "l"
"mu" = "m"
"new" = "n"
"zee" = "x"
"pie" = "p"
"row" = "r"
"sigma" = "s"
"tau" = "t"
"upsilon" = "u"
"phi" = "f"
"chi" = "q"
"sigh" = "c"
"omega" = "w"

[misc_sn_keys]
"fraction" = "c-f"
"over" = "cs-left, c-f"
"(super [script] | to the power)" = "c-h"
"sub [script]" = "c-l"
"squared" = "c-h, 2, right"
"cubed" = "c-h, 3, right"
"inverse" = "c-h, minus, 1, right"
"(parens | parentheses | prens)" = "c-0"
"(squares | square brackets)" = "c-6"
"absolute" = "c-backslash"
"norm" = "cs-backslash"
"chi squared" = "c-g, q, c-h, 2, right"
"(radical | root | square root)" = "c-r"
"summation" = "c-7"
"sum to N" = "s, m, i, t, o, n"
"expectation" = "s-e, c-0"
"given" = "ctrl:down, t, h, i, n, s, p, a, c, e, ctrl:up, bar, ctrl:down, t, h, i, n, s, p, a, c, e, ctrl:up"
"variance of" = "s-v, a, r, c-0"
"covariance of" = "s-c, o, v, c-0"
"prime" = "apostrophe"
#
"label above" = "f10, i, down:11, enter/25, a, enter"
"label below" = "f10, i, down:11, enter/25, b, enter"
"thin space" = "ctrl:down, t, h, i, n, s, p, a, c, e, ctrl:up"
"thick space" = "ctrl:down, q, u, a, d, ctrl:up"


[tex_symbols]
# operators
"integral" = "int"
"double integral" = "iint"
"triple integral" = "iiint"
"times" = "times"
"divide" = "div"
"C dot" = "cdot"
"plus or minus" = "pm"
"partial" = "partial"
"infinity" = "infty"
"nabla" = "nabla"
# trig
"sine" = "sin"
"cosine" = "cos"
"tangent" = "tan"
"secant" = "sec"
"cosecant" = "csc"
"cotangent" = "cot"
"arc sine" = "arcsin"
"arc cosine" = "arccos"
"arc tan" = "arctan"
"hyperbolic sine" = "sinh"
"hyperbolic cosine" = "cosh"
"hyperbolic cotangent" = "coth"
"hyperbolic tangent" = "tanh"
# functions
"argument" = "arg"
"degree" = "deg"
"determinant" = "det"
"dimension" = "dim"
"exponential" = "exp"
"(natural (log | logarithm) | log natural)" = "ln"
"logarithm" = "log"
"maximum" = "max"
"minimum" = "min"
"product" = "prod"
"limit" = "lim"
"infimum" = "inf"
"supremum" = "sup"
"probability" = "Pr"
# relations
"there exists" = "exists"
"member" = "in"
"for all" = "forall"
"[is] not equal [to]" = "neq"
"[is] greater [than] [or] equal [to]" = "geq"
"[is] less [than] [or] equal [to]" = "leq"
"[is] approximately [equal] [to]" = "approx"
"proportional [to]" = "propto"
"preference less [than]" = "prec"
"preference less equal" = "preceq"
"preference greater [than]" = "succ"
"preference greater equal" = "succeq"
# sets
# "subset" = "subset"
# "superset" = "supset"
# "strict subset" = "subsetneq"
# "strict superset" = "supsetneq"
# "intersection" = "cap"
# "union" = "cup"
# logic
"logic and" = "land"
"logic or" = "lor"
"logic not" = "lnot"
#
"dot dot dot" = "dots"
"left arrow" = "leftarrow"
"right arrow" = "rightarrow"
"up arrow" = "uparrow"
"down arrow" = "downarrow"
"left right arrow" = "leftrightarrow"
"maps to" = "mapsto"
"oh plus" = "oplus"
"(oh times | kronecker)" = "otimes"
"big oh plus" = "bigoplus"
"big oh times" = "bigotimes"
#
"diagonal dots" = "ddots"
"horizontal dots" = "cdots"
"vertical dots" = "vdots"

[accents]
"hat" = "c-caret"
"tilde" = "c-tilde"
"dot" = "c-dot"
"double dot" = "c-dquote"
"bar" = "c-underscore"
"arrow" = "c-minus"

[denominators]
"(half | halves)" = 2
"(third | thirds)" = 3
"(quarter | quarters | fourth | fourths)" = 4
"(fifth | fifths)" = 5
"(sixth | sixths)" = 6
"(seventh | sevenths)" = 7
"(eighth | eighths)" = 8
"(ninth | ninths)" = 9
"(tenth | tenths)" = 10

[misc_sn_text]
"miscellaneous text" = "test"


[control]
"new file"                         = "f10, f, enter"
"open file"                        = "c-o"
"save file"                        = "f10, f, s"
"save as"                          = "f10, f, down:5, enter"
"print file"                       = "c-p"
"export document"                  = "f10, f, down:7, enter"
"page preview"                     = "f10, f, down:17, enter"
"toggle math"                      = "c-m"
"toggle text"                      = "c-t"
"body math"                        = "a-2, down, enter"
"body text"                        = "a-2, down:2, enter"
"(begin | insert) [bulleted] list" = "a-1, down:2, enter"
"(begin | insert) numbered list"   = "a-1, down:4, enter"
"end [(bulleted | numbered)] list" = "a-1, up, enter"
"insert normal text"               = "a-3, down, enter"
"insert big text"                  = "a-3, down:2, enter"
"insert small text"                = "a-3, down:9, enter"
"insert bold text"                 = "a-3, down:3, enter"
"insert italic text"               = "a-3, down:6, enter"
"insert bold symbols"              = "a-3, down:4, enter"
"insert centred text"              = "a-2, down:3, enter"
"insert left text"                 = "a-2, down:4, enter"
"insert right text"                = "a-2, down:5, enter"
"insert quotation"                 = "a-2, down:11, enter"
"insert (heading | title) [one]"   = "a-2, down:6, enter"
"insert (heading | title) two"     = "a-2, down:7, enter"
"insert (heading | title) three"   = "a-2, down:8, enter"
"insert (heading | title) four"    = "a-2, down:9, enter"
"insert (heading | title) five"    = "a-2, down:10, enter"
"evaluate"                         = "c-e"


[units]
# Activity
"Becquerels" = "uBq"
"Curies" = "uCi"
# Amount
"Attomoles" = "uamol"
"Examoles" = "uEmol"
"Femtomoles" = "ufmol"
"Gigamoles" = "uGmol"
"Kilomoles" = "ukmol"
"Megamoles" = "uMmol"
"Micromoles" = "umcmol"
"Millimoles" = "ummol"
"Moles" = "umol"
"Nanomoles" = "unmol"
"Petamoles" = "uPmol"
"Picomoles" = "upmol"
"Teramoles" = "uTmol"
# Area
"Acres" = "uacre"
"Hectares" = "uhectare"
"Square feet" = ["uft", "c-h, 2, right"]
"Square inches" = ["uin", "c-h, 2, right"]
"Square metres" = ["ume", "c-h, 2, right"]
# Current
"Amperes" = "uA"
"Kiloamperes" = "ukA"
"Microamperes" = "umcA"
"Milliamperes" = "umA"
"Nanoamperes" = "unA"
# Capacitance
"Farads" = "uF"
"Microfarads" = "umcF"
"Millifarads" = "umF"
"Nanofarads" = "unF"
"Picofarads" = "upF"
# Charge
"Coulombs" = "uCo"
# Conductors
"Kilosiemens" = "ukS"
"Microsiemens" = "umcS"
"Millisiemens" = "umS"
"Siemens" = "uS"
# Potential difference
"Kilovolts" = "ukV"
"Megavolts" = "uMV"
"Microvolts" = "umcV"
"Millivolts" = "umV"
"Nanovolts" = "unV"
"Picovolts" = "upV"
"Volts" = "uV"
# Resistance
"Gigaohms" = "uGohm"
"Kiloohms" = "ukohm"
"Megaohms" = "uMohm"
"Milliohms" = "umohm"
"Ohms" = "uohm"
# Energy
"British thermal unit" = "uBtu"
"Calories" = "ucal"
"Electron volts" = "ueV"
"Ergs" = "uerg"
"Gigaelectronvolts" = "uGeV"
"Gigajoules" = "uGJ"
"Joules" = "uJ"
"Kilocalories" = "ukcal"
"Kilojoules" = "ukJ"
"Megaelectronvolts" = "uMeV"
"Megajoules" = "uMJ"
"Microjoules" = "umcJ"
"Millijoules" = "umJ"
"Nanojoules" = "unJ"
# Force
"Dynes" = "udyn"
"Kilonewtons" = "ukN"
"Meganewtons" = "uMN"
"Micronewtons" = "umcN"
"Millinewtons" = "umN"
"Newtons" = "uN"
"Ounce force" = "uozf"
"Pound force" = "ulbf"
# Frequency
"Exahertz" = "uEHz"
"Gigahertz" = "uGHz"
"Hertz" = "uHz"
"Kilohertz" = "ukHz"
"Megahertz" = "uMHz"
"Petahertz" = "uPHz"
"Terahertz" = "uTHz"
# Illuminance
"Footcandle" = "ufc"
"Lux" = "ulx"
"Phot" = "uphot"
# Length
"Angstrom" = "uan"
"Attometers" = "uame"
"Centimeters" = "ucm"
"Decimeters" = "udme"
"Femtometers" = "ufme"
"Feet" = "uft"
"Inches" = "uin"
"Kilometers" = "ukme"
"Meters" = "ume"
"Micrometers" = "umcme"
"Miles" = "umi"
"Millimeters" = "umme"
"Nanometers" = "unme"
"Picometers" = "upme"
# Luminance
"Candela" = "ucd"
"Lumens" = "ulm"
# Magnetic flux
"Maxwells" = "uMx"
"Microwebers" = "umcWb"
"Milliwebers" = "umWb"
"Nanowebers" = "unWb"
"Webers" = "uWb"
# Magnetic flux density
"Gauss" = "uGa"
"Microteslas" = "umcT"
"Milliteslas" = "umT"
"Nanoteslas" = "unT"
"Picoteslas" = "upT"
"Teslas" = "uTe"
"Henries" = "uHe"
"microhenries" = "umcH"
"millihenries" = "umH"
# Mass
"Atomic mass units" = "uu"
"Centigrams" = "ucg"
"Decigrams" = "udg"
"Grams" = "ugr"
"Kilograms" = "ukg"
"Micrograms" = "umcg"
"Milligrams" = "umg"
"Pounds" = "ulbm"
"Slug" = "uslug"
# Angle
"degrees" = "udeg"
"Microradians" = "umcrad"
"Milliradians" = "umrad"
"Minutes of angle" = "udmn"
"Seconds of angle" = "uds"
"Radians" = "urad"
"Steradian" = "usr"
# Power
"Gigawatts" = "uGW"
"Horsepowers" = "uhp"
"Kilowatts" = "ukW"
"Megawatts" = "uMW"
"Microwatts" = "umcW"
"Milliwatts" = "umW"
"Nanowatts" = "unW"
"Watts" = "uWa"
# Pressure
"Atmospheres" = "uatm"
"Bar" = "ubar"
"Kilobar" = "ukbar"
"Kilopascals" = "ukPa"
"Megapascals" = "uMPa"
"Micropascals" = "umcPa"
"Millibar" = "umbar"
"Millimeters of Mercury" = "ummHg"
"Pascals" = "uPa"
"Torrs" = "utorr"
# Temperature
"Celsiuss" = "ucel"
"Fahrenheits" = "ufahr"
"Kelvins" = "uK"
# Time
"Attoseconds" = "uas"
"Days" = "uda"
"Femtoseconds" = "ufs"
"Hours" = "uhr"
"Microseconds" = "umcs"
"Milliseconds" = "ums"
"Minutes" = "umn"
"Nanoseconds" = "uns"
"Picoseconds" = "ups"
"Seconds" = "use"
"Years" = "uy"
# Volume
"Cubic feet" = ["uft", "c-h, 3, right"]
"Cubic inches" = ["uin", "c-h, 3, right"]
"Cubic metres" = ["ume", "c-h, 3, right"]
"Gallons" = "ugal"
"Liters" = "uli"
"Milliliters" = "uml"
"Pints" = "upint"
"Quarts" = "uqt"
