ccr_path = "config/ccr.toml"
clipboard_path = "config/clipboard.toml"
dragon_path = "C:/Program Files (x86)/Nuance/NaturallySpeaking15/Program/natspeak.exe"
# editor_path = "C:/Windows/notepad.exe"
browser_path = "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"
editor_path = "C:/Program Files/Sublime Text 3/sublime_text.exe"
ccr_modules = ["core",
			"sn_mathematics",
			"lyx_mathematics",
			"latex",
			"latex_maths",
			"alias",
			"file_dialogue",
			"go",
			"gitbash",
			"python",
			"r",
			"markdown",
			"sublime"
			]
app_modules = [
			"lyx",
			"chrome",
			"fman",
			"dragon",
			"photoshop",
			"rstudio",
			"explorer",
			"github",
			"sumatrapdf",
			"bringme",
			"pdfsave",
			"oxmetrics",
			"spotify",
			"powershell",
			# "accessibility"
			]
max_ccr_repetitions = 13
keypress_wait = 0.05
alternative_letters = true
alternative_directions = true
use_aenea = false
use_wsr = false