pronunciation      = "SQL"
title_contexts     = [".sql"]
function_prefix    = "fun"
template_prefix    = "template"
"logical_prefix" = "lodge"

[functions]
"average"          = "AVG"
"count"            = "COUNT"
"length" = "LENGTH"
"max"              = "MAX"
"min"              = "MIN"
"sum"              = "SUM"

[commands]
"case when"        = ["CASE WHEN  END", "left:4"]
"delete"           = "DELETE "
"distinct"         = "DISTINCT "
"from"             = "FROM "
"full join"        = "FULL JOIN "
"group by"         = "GROUP BY "
"having"           = "HAVING "
"inner join"       = "INNER JOIN "
"insert into"      = "INSERT INTO "
"is not null"      = " IS NOT NULL"
"is null"          = " IS NULL"
"left join"        = "LEFT JOIN "
"limit"            = "LIMIT "
"normal join"      = "JOIN "
"not equals"       = " <> "
"not like"         = "NOT LIKE "
"on columns"       = "ON "
"order ascending"  = "ASC "
"order by"         = "ORDER BY "
"order descending" = "DESC "
"right join"       = "RIGHT JOIN "
"select every"     = "SELECT *"
"select"           = "SELECT "
"union"            = "UNION "
"update"           = "UPDATE"
"using"            = "USING "
"value null"       = "NULL"
"where"            = "WHERE "
"with as"          = ["WITH  AS ()", "left, enter:2, up:2, end, left:5"]

[logicals]
"and"              = " AND "
"as"               = " AS "
"between"          = " BETWEEN "
"in"               = " IN "
"is"               = " IS "
"is not"           = " IS NOT "
"like"             = " LIKE "
"or"               = " OR "
"on"               = " ON "
"then"             = " THEN "
"not"              = " NOT "

[templates]
