pronunciation      = "SQL"
title_contexts     = [".sql"]
function_prefix    = "fun"
template_prefix    = "template"
"logical_prefix" = "lodge"

[functions]
"average"          = "AVG() "
"count"            = "COUNT() "
"max"              = "MAX() "
"min"              = "MIN() "
"sum"              = "SUM() "

[commands]
"from"             = "FROM "
"select"           = "SELECT "
"select every"     = "SELECT *"
"where"            = "WHERE "
"delete"           = "DELETE "
"update"           = "UPDATE"
"insert into"      =  "INSERT INTO "
"between"          = " BETWEEN "
"group by"         = "GROUP BY "
"not equals"       = " <> "
"like"             = "LIKE "
"not like"         = "NOT LIKE "
"order by"         = "ORDER BY "
"order ascending"  = "ASC "
"order descending" = "DESC "
"left join"        = "LEFT JOIN "
"inner join"       = "INNER JOIN "
"right join"       = "RIGHT JOIN "
"full join"        = "FULL JOIN "
"normal join"      = "JOIN "
"on columns"       = "ON "
"union"            = "UNION "
"using"            = "USING "
"is null"          = " IS NULL"
"is not null"      =  " IS NOT NULL"
"as"               = " AS "
"distinct"         = "DISTINCT "
"having"           =  "HAVING "
"limit"            =  "LIMIT "

[logicals]
"and"              = "AND "
"or"               = " OR "
"in"               = " IN "
"not"              = " NOT "

[templates]
